spring.application.name=Accommodation
server.port=8085


spring.datasource.url=jdbc:postgresql://localhost:5433/accommodation
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.hikari.initializationFailTimeout=0

